version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: hotel-rabbitmq
    ports:
      - "5672:5672" # Application port
      - "15672:15672" # Web UI (login/password: guest/guest)
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hotel-scenarios-app
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
    env_file:
      - .env
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672 # Force the app to connect to the neighboring container
    restart: unless-stopped
